# Generated by Django 4.0.4 on 2022-06-19 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_bodovi_course_ects_rename_ime_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisni_list',
            name='korisnik_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='upisni_list',
            name='predmet_id',
        ),
        migrations.AddField(
            model_name='upisni_list',
            name='predmet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='upisni_list',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
