# Generated by Django 4.0.4 on 2022-06-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_predmeti_predmet_rename_upisi_upis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predmet',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Upis',
            new_name='Upisni_list',
        ),
    ]
