# Generated by Django 4.0.4 on 2022-06-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_predmet_course_rename_upis_upisni_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='bodovi',
            new_name='ects',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='ime',
            new_name='name',
        ),
    ]
