# Generated by Django 4.0.4 on 2022-06-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_upisni_list_korisnik_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisni_list',
            name='status',
            field=models.CharField(choices=[('enr', 'enrolled'), ('pass', 'passed')], max_length=50),
        ),
    ]
