# Generated by Django 4.0.4 on 2022-06-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_upisni_list_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upisni_list',
            old_name='korisnik_id',
            new_name='korisnik',
        ),
        migrations.RenameField(
            model_name='upisni_list',
            old_name='predmet_id',
            new_name='predmet',
        ),
    ]
