# Generated by Django 4.0.4 on 2022-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_korisnik_id_upisni_list_korisnik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='izborni',
            field=models.CharField(choices=[('da', 'DA'), ('ne', 'NE')], max_length=50),
        ),
    ]
