# Generated by Django 4.0.4 on 2022-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_course_izborni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
